version: '3.8'
services:
  # api:
  #   image: node:14-alpine
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - 3000:3000
  #   command: >
  #     sh -c "
  #       rm -f -r node_modules/
  #       npm i &&
  #       npm run dev"
  #   depends_on:
  #     - db_admin

  db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: phonebey_api

  db_admin:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
